### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [gicentre/prettier-plugin-elm#30]
Hi!

The Prettier team is currently working on v3(still alpha).
v3 will include breaking changes to the plugin interface.
Please see https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.2 for more information.

I created this issue to help major plugins migrate to Prettier v3.

Myself and @fisker have created a migration guide which you can see here:

https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by kachkaev** [comment]
👋 @jwoLondon! Would now be a good time to experiment with Prettier v3? I hope I can produce a version that is compatible with both Prettier v2 and v3, but if this is impossible, when would you recommend me to _not_ release breaking changes?

**Comment by jwoLondon** [comment]
Thanks Alex. Yes please, that would be great. If it turns out to create any breaking changes, we can discuss timing via email.

**Comment by kachkaev** [comment]
It turned out that the existing version ([0.8.0](https://github.com/gicentre/prettier-plugin-elm/releases/tag/v0.8.0)) was compatible with Prettier 3 and did not need any changes. I released [0.9.0](https://github.com/gicentre/prettier-plugin-elm/releases/tag/v0.9.0) with newer dependencies and some internal refactoring anyway. #36 confirms plugin compatibility with Prettier v1, v2 and v3; the repo uses 3.0.0-alpha.4 internally.

User experience should remain the same, I don’t expect any breaking changes except for the dropped Node 12 support (#33).
